[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0.2"
nalgebra = { path = "../nalgebra" }
histogram = "0.6.9"
streaming-stats = "0.2.3"
